# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: user
      POSTGRES_DB: postgresdbb
    ports:
      - "5432:5432"
    networks:
    - backend

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    env_file: .env
    ports:
      - '5050:80'
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge


# to connect pgadmin : docker container ls
# Get the id of postgres, then docker inspect [id]
# then get the IP and add it to pgadmin

# services:
#   db:
#     image: postgres
#     restart: always
#     env_file: .env
#     container_name: postgres
#     ports:
#       - '5432:5432'
#     # volumes:
#     #   - ./pgdata:/var/lib/postgresql/data:z



#   # app:
  #   build:
  #     context: backend
  #     dockerfile: Dockerfile
  #   container_name: nestjs
  #   environment:
  #     - PORT=${PORT}
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./src:/app/src
    # restart: "always"
