# Use postgres/example user/password credentials
# version: '3.9'

services:

  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: user
      POSTGRES_DB: postgresdbb
    ports:
      - "5432:5432"
    networks:
    - backend

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    env_file: .env
    ports:
      - '5050:80'
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - ./pgadmin/config/servers.json:/pgadmin4/servers.json  # Montez le fichier de configuration
      - ./pgadmin/config/config_distro.py:/pgadmin4/config_distro.py
      - ./pgadmin/config/logs:/var/log/pgadmin


networks:
  backend:
    driver: bridge


# to connect pgadmin : docker container ls
# Get the id of postgres, then docker inspect [id]
# then get the IP and add it to pgadmin
